[terminal]
shell= "/Users/wesley.adriann/.cargo/bin/zellij"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 14 

[window]
startup_mode = "Windowed"

[general]
import = [
  # "./tokyo-night-storm.toml"
  # "./catppuccin-macchiato.toml"
  "./catppuccin-mocha.toml"
]

