[terminal]
shell= "/Users/wesley.adriann/.cargo/bin/zellij"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 12.5

[window]
startup_mode = "Maximized"

[general]
import = [
  "./tokyo-night-storm.toml"
]

